name: LobbySystem
version: '${project.version}'
main: de.murmelmeister.lobbysystem.LobbySystem
api-version: 1.21
authors: [ Murmelmeister ]
description: Is a LobbySystem plugin.
website: https://www.youtube.com/Murmelmeister

commands:
  build:
    usage: /<command> [player]
    description: Set a player in/or out of build mode.
  deathheight:
    usage: /<command>
    description: Shows the current death height.
  lobbysystemreload:
    usage: /<command>
    description: Reloads the LobbySystem plugin.
    alias: [ lsreload, lsr, lobbyreload ]
  setdeathheight:
    usage: /<command>
    description: Set the death height.
  setspawn:
    usage: /<command>
    description: Set the spawn location.
  spawn:
    usage: /<command>
    description: Teleport a player to the spawn location.